dist: bionic
language: ruby
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
services:
  - memcached
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - travis_retry gem install bundler -v "<2"
notifications:
  email: false
