import:
  - twingly/travis-ci:config/notifications.yml@master
  - twingly/travis-ci:config/ubuntu.yml@master
  - twingly/travis-ci:config/ruby.yml@master
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
services:
  - memcached
