name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211

    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1.6, 3.2.4, 3.3.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake
