name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6.7, 2.7.3, 3.0.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake
